[package]
name = "use-scroll-example"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus-util.workspace = true
dioxus.workspace = true

[features]
default = ["desktop"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]