[package]
name = "dioxus_storage"
version = "0.1.0-alpha.1"

description = "Local and persistent storage utilities for Dioxus."
readme = "./README.md"
keywords = ["gui", "dioxus", "hooks"]
categories = ["gui", "wasm"]

edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
dioxus = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
futures-util = { workspace = true }
cfg-if = { workspace = true }

rustc-hash = "1.1.0"
ciborium = "0.2.2"
once_cell = "1.17.0"
dioxus-signals = { workspace = true, features = ["serialize"] }
serde.workspace = true
yazi = "0.1.4"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
directories = "4.0.1"

[target.'cfg(target_family = "wasm")'.dependencies]
web-sys = { workspace = true, features = ["Window", "Storage", "StorageEvent"] }
wasm-bindgen = { workspace = true }
