[package]
name = "dioxus-clipboard"
version = "0.1.0"

description = "Access the device clipboard from your Dioxus apps."
readme = "./README.md"
keywords = ["gui", "dioxus", "hooks"]
categories = ["gui", "wasm"]

edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
copypasta = "0.10.1"
dioxus = { workspace = true }
