[package]
name = "dioxus-geolocation"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true }
cfg-if = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }

[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen = { workspace = true }
js-sys = { workspace = true }
web-sys = { workspace = true, features = [
    "Window",
    "Navigator",
    "Geolocation",
    "PositionOptions",
] }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.48.0", features = [
    "Foundation",
    "Devices_Geolocation",
] }
