name: Rust

on:
  push:
    branches:
      - main
    paths:
      - sdk/**
      - examples/**
      
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
    paths:
      - sdk/**
      - examples/**

env:
  CARGO_TERM_COLOR: always

jobs:
  # Rust fmt
  fmt:
      if: github.event.pull_request.draft == false
      name: Rustfmt
      runs-on: ubuntu-latest
      steps:
        - uses: dtolnay/rust-toolchain@stable
        - uses: Swatinem/rust-cache@v2
        - run: rustup component add rustfmt
        - uses: actions/checkout@v3
        - run: cargo fmt --all -- --check
  # Clippy
  clippy:
    if: github.event.pull_request.draft == false
    name: Clippy
    runs-on: windows-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: rustup target add wasm32-unknown-unknown
      - run: rustup component add clippy
      - uses: actions/checkout@v3
      - run: cargo clippy --package dioxus-sdk --target wasm32-unknown-unknown --tests --features wasm-testing -- -D warnings
      - run: cargo clippy --package dioxus-sdk --tests --features desktop-testing -- -D warnings
