# Tests to make sure features are setup for running on different platforms & that features run correctly
name: Testing

on:
  push:
    branches:
      - main
    paths:
      - packages/**
      - examples/**
      
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
    paths:
      - packages/**
      - examples/**

env:
  CARGO_TERM_COLOR: always

jobs:
  wasm:
    if: github.event.pull_request.draft == false
    name: WASM
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup target add wasm32-unknown-unknown
    - uses: Swatinem/rust-cache@v2
    - run: cargo build --all-targets --workspace --exclude *-example --verbose --target wasm32-unknown-unknown --all-features
    # need to run tests here
    
  desktop:
    if: github.event.pull_request.draft == false
    name: Desktop
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - run: cargo build --all-targets --workspace --verbose --all-features
    - run: cargo test --all-targets --workspace --verbose --all-features
    - run: cargo test --workspace --verbose --all-features --doc
